---
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

addons:
  code_climate:
    repo_token: ca73bff12055cf8ba8b28633fc46a96d2d6f932359c5ada7ddbbc16f54f6e79a
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - COVERAGE=true EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - bower --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
